server:
  port: 19093 # Product ???? ??? ?? ??

spring:
  application:
    name: product-service # ?????? ??
  datasource:
    url: jdbc:mysql://localhost:3306/product_db # MySQL URL
    username: root # MySQL ????
    password: 1q2w3e4r!! # MySQL ????
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ???? ???
  jpa:
    hibernate:
      ddl-auto: update # JPA? ?? ??? ?? ????
    show-sql: true # SQL ??? ??? ??
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka ?? URL

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 100%
