server:
  port: 19095 # Auth 서비스 포트 번호

spring:
  application:
    name: auth-service # 애플리케이션 이름

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db # MySQL URL
    username: root # 데이터베이스 사용자명
    password: 1q2w3e4r!! # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버
  jpa:
    hibernate:
      ddl-auto: update # JPA Hibernate 설정
    show-sql: true # SQL 로그 출력

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka URL

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1" # JWT 서명용 비밀키
    # JWT 비밀키

    access-expiration: 3600000 # JWT 만료 시간 (ms)
